from uprotocol.uri.serializer.longuriserializer import LongUriSerializer
from uprotocol.proto.uri_pb2 import UUri, UAuthority, UEntity, UResource 
from uprotocol.uri.validator.urivalidator import UriValidator

print("ex1")
auth = UAuthority(name="authority_name_nameName", ip=b'ipaddress.ip.ip.address')
enti = UEntity(name="name of entity", id=101, version_major=64, version_minor=32)
ures = UResource(name="resource name", instance="resource instance", message="message of resource", id=5)
uri = UUri(authority=auth, entity=enti, resource=ures)
print(uri)
print("------")
serialized: str = LongUriSerializer().serialize(uri)
deserialized: UUri = LongUriSerializer().deserialize(serialized)
print(deserialized)

print(UriValidator.validate(deserialized))


print("ex2")
auth = UAuthority( id=b'ipaddress.ip.ip.address')
enti = UEntity(name="name of entity", )
ures = UResource(name="resource name",)
uri = UUri(authority=auth, entity=enti, resource=ures)
print(uri)
print("--------")
serialized: str = LongUriSerializer().serialize(uri)
print("serialize:", serialized)
# deserialize(serialized)
deserialized: UUri = LongUriSerializer().deserialize(serialized)
print("deserialize:", type(deserialized),  deserialized)

print("ex3")
serialized: str = LongUriSerializer().deserialize("//")
print(serialized)

print("ex4")
deserialized: UUri = LongUriSerializer().deserialize("/body.access/1/rpc.response ")
print(deserialized)
print(UriValidator.validate(deserialized))

print("rpc method ex1")
auth = UAuthority(name="")
enti = UEntity(id=5, name="petapp", version_major=1, version_minor=0)
ures = UResource(id=32768, name="rpc")
uri = UUri(entity=enti, resource=ures)
print(uri)
print(LongUriSerializer().serialize(uri))
deserialized: UUri = LongUriSerializer().deserialize("/petapp/1/rpc")
print("deserialized:", deserialized)
print(UriValidator.validate_rpc_method(deserialized))
print(0x8000)

print("rpc_response ex1")
auth = UAuthority(name="name")
enti = UEntity(id=5, name="neelam", version_major=0, version_minor=0)
ures = UResource(id=32768, name="rpc", instance="response", message="")
uri = UUri(authority=auth, entity=enti, resource=ures)
print(uri)
print(LongUriSerializer().serialize(uri))
deserialized: UUri = LongUriSerializer().deserialize(LongUriSerializer().serialize(uri)) # LongUriSerializer().deserialize("/neelam//rpc.response")
print(deserialized)
print(UriValidator.validate_rpc_response(deserialized))

print("rpc response ex2")
deserialized: UUri = LongUriSerializer().deserialize("/entity name//dummyName.notResponse")
print("deserialized:", deserialized)
print(UriValidator.validate_rpc_method(deserialized))

print("is_resolved ex1")
auth = UAuthority(id=b"id", name="")
enti = UEntity(id=5, name="", version_major=0)
ures = UResource(id=5, name="", instance="", message="")
uri = UUri(authority=auth, entity=enti)
print(uri)
serialized = LongUriSerializer().serialize(uri)
print(serialized)
deserialized: UUri = LongUriSerializer().deserialize(serialized) # LongUriSerializer().deserialize("/neelam//rpc.response")
print(deserialized)
print(UriValidator.is_resolved(deserialized))

# deserialized: UUri = LongUriSerializer().deserialize("///hartley/23/") # LongUriSerializer().deserialize("/neelam//rpc.response")
# print(deserialized)
# print(UriValidator.is_resolved(deserialized))