# -------------------------------------------------------------------------
#
# Copyright (c) 2024 General Motors GTO LLC
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# License); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# AS IS BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2024 General Motors GTO LLC
# SPDX-License-Identifier: Apache-2.0
#
# -------------------------------------------------------------------------

Feature: UAttributes Validation

  Scenario Outline: Validate different types of UAttributes
    Given "uE1" creates data for "uattributes_validate"
      And sets "validation_method" to "<val_method>"
      And sets "validation_type" to "<val_type>"
      And sets "attributes.source.authority.name" to "<source_authority_name>"
      And sets "attributes.source.entity.name" to "<source_entity_name>"
      And sets "attributes.source.entity.version_major" to "<source_version_major>"
      And sets "attributes.source.resource.name" to "<source_resource_name>"
      And sets "attributes.sink.authority.name" to "<sink_authority_name>"
      And sets "attributes.sink.entity.name" to "<sink_entity_name>"
      And sets "attributes.sink.entity.version_major" to "<sink_version_major>"
      And sets "attributes.sink.resource.name" to "<sink_resource_name>"
      And sets "attributes.sink.resource.instance" to "<sink_resource_instance>"
      And sets "attributes.sink.resource.id" to "<sink_resource_id>"
      And sets "attributes.priority" to "<priority>"
      And sets "attributes.type" to "<message_type>"
      And sets "id" to "<id_type>"
      And sets "attributes.ttl" to "<ttl>"
      And sets "attributes.permission_level" to "<permission_level>"
      And sets "attributes.comm_status" to "<comm_status>"
      And sets "reqid" to "<reqid_type>"

    When sends "uattributes_validate" request
      Then receives validation result as "<expected_status>"
      And  receives validation message as "<expected_message>"

    Examples:
      | val_type                     | val_method               | source_authority_name         | source_entity_name   | source_version_major | source_resource_name | sink_authority_name               | sink_entity_name          | sink_version_major | sink_resource_name    | sink_resource_instance | sink_resource_id | priority              | message_type               | id_type   | token | ttl  | permission_level | comm_status | reqid_type | expected_status | expected_message                                                                           |
      | get_validator                |                          | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      |           |       |      |                  |             |            | none            | UAttributesValidator.Publish                                                               |
      | get_validator                |                          | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_REQUEST      |           |       | 1000 |                  |             |            | none            | UAttributesValidator.Request                                                               |
      | get_validator                |                          | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     |           |       |      |                  |             |            | none            | UAttributesValidator.Response                                                              |
      | get_validator                |                          | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_NOTIFICATION |           |       |      |                  |             |            | none            | UAttributesValidator.Notification                                                          |
      | get_validator                |                          |                               |                      |                      |                      |                                   |                           |                    |                       |                        |                  |                       |                            |           |       |      |                  |             |            | none            | UAttributesValidator.Publish                                                               |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | True            | none                                                                                       |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 1000 | 2                | 3           |            | True            | none                                                                                       |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS0         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       |      |                  |             | uprotocol  | False           | Wrong Attribute Type [UMESSAGE_TYPE_RESPONSE]                                              |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | False           | Uri is empty.                                                                              |
      |                              | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_REQUEST      | uprotocol |       | 1000 |                  |             |            | True            | none                                                                                       |
      |                              | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_REQUEST      | uprotocol |       | 1000 | 2                | 3           | uprotocol  | True            | none                                                                                       |
      |                              | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       | 1000 |                  |             | uprotocol  | False           | Wrong Attribute Type [UMESSAGE_TYPE_RESPONSE]                                              |
      |                              | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_REQUEST      | uprotocol |       | 1000 |                  |             |            | False           | Uri is empty.                                                                              |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       |      |                  |             | uprotocol  | True            | none                                                                                       |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       |      | 2                | 3           | uprotocol  | True            | none                                                                                       |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_NOTIFICATION | uprotocol |       |      |                  |             |            | False           | Wrong Attribute Type [UMESSAGE_TYPE_NOTIFICATION],Missing correlationId                    |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       |      |                  |             |            | False           | Missing Sink,Missing correlationId                                                         |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS4         | UMESSAGE_TYPE_RESPONSE     | uprotocol |       |      |                  |             |            | False           | Missing correlationId                                                                      |
      | is_expired                   | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | False           | none                                                                                       |
      | is_expired                   | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 0    |                  |             |            | False           | none                                                                                       |
      | is_expired                   | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 10000|                  |             |            | False           | none                                                                                       |
      | is_expired                   | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 1    |                  |             |            | True            | none                                                                                       |
      | validate_ttl                 | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 100  |                  |             |            | True            | none                                                                                       |
      | validate_sink                | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | False           | Uri is empty.                                                                              |
      | validate_sink                | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | True            | none                                                                                       |
      | validate_req_id              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             | uprotocol  | True            | none                                                                                       |
      | validate_type                | notification_validator   | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS0         | UMESSAGE_TYPE_NOTIFICATION | uprotocol |       |      |                  |             | uprotocol  | True            | none                                                                                       |
      | validate_sink                | notification_validator   | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS0         | UMESSAGE_TYPE_NOTIFICATION | uprotocol |       |      |                  |             | uprotocol  | True            | none                                                                                       |
      | validate_sink                | notification_validator   | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_NOTIFICATION | uprotocol |       |      |                  |             | uprotocol  | False           | Missing Sink                                                                               |
      | validate_permission_level    | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      | 3                |             | uprotocol  | True            | none                                                                                       |
      | validate_permission_level    | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | default                           |                           |                    |                       |                        |                  | UPRIORITY_CS0         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      | 0                |             | uprotocol  | False           | Invalid Permission Level                                                                   |
      |                              | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS4         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       |      |                  |             |            | False           | Wrong Attribute Type [UMESSAGE_TYPE_PUBLISH],Missing TTL,Missing Sink                      |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS6         | UMESSAGE_TYPE_REQUEST      | uprotocol |       | 1000 | 2                | 3           | uprotocol  | False           | Wrong Attribute Type [UMESSAGE_TYPE_REQUEST]                                               |
      |                              | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS6         | UMESSAGE_TYPE_PUBLISH      | uprotocol |       | 1000 | 2                | 3           |            | False           | Wrong Attribute Type [UMESSAGE_TYPE_PUBLISH],Missing Sink,Missing correlationId            |
      |                              | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS6         | UMESSAGE_TYPE_PUBLISH      | uprotocol | null  |      |                  |             |            | True            | none                                                                                       |
      | validate_id                  | publish_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  |                                   |                           |                    |                       |                        |                  | UPRIORITY_CS6         | UMESSAGE_TYPE_PUBLISH      |           |       |      |                  |             |            | False           | Missing id                                                                                 |
      | validate_id                  | notification_validator   | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS6         | UMESSAGE_TYPE_NOTIFICATION |           |       |      |                  |             |            | False           | Missing id                                                                                 |
      | validate_id                  | request_validator        | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS6         | UMESSAGE_TYPE_REQUEST      |           |       | 1000 |                  |             |            | False           | Missing id                                                                                 |
      | validate_id                  | response_validator       | vcu.someVin.veh.ultifi.gm.com | petapp.ultifi.gm.com | 1                    | rpc                  | vcu.someVin.veh.ultifi.gm.com     | petapp.ultifi.gm.com      | 1                  | rpc                   | response               | 0                | UPRIORITY_CS6         | UMESSAGE_TYPE_RESPONSE     |           |       |      |                  |             | uprotocol  | False           | Missing id                                                                                 |