= Eclipse uProtocol TCK Library 
:toc:

== Overview

This library implements the uProtocol Test Compatibility Kit for the use of a Test Manager and Test Agents. A Test Manager will be responsible for sending commands to multiple connected Test Agents. The Test Agents, in turn, will carry out the tests specified in the commands, and return results back to the Test Manager for validation and processing.



== Getting Started

=== Prerequisites
Set up up-python

----
$ git clone https://github.com/eclipse-uprotocol/up-python.git
$ cd up-python
$ pip install .
----

=== Importing the up-tck-python
 
Set up upclient-socket-python local repository and install
[source]
----
$ git clone https://github.com/eclipse-uprotocol/up-tck.git
$ cd up-tck/python
$ pip install .
----
*This will install the up-tck-python, making its classes and modules available for import in your python code.*

=== Building Java Test Agent Jar

If you would like to run any tests with the Java Test Agent, follow these instructions:

1. In Eclipse, open the existing Java Maven project located in the folder up-tck\java\java_test_agent 
* If there are errors when importing a java folder, here is a guide: https://crunchify.com/mavenmvn-clean-install-update-project-and-project-clean-options-in-eclipse-ide-to-fix-any-dependency-issue/
* If Maven option is not found after right-clicking the java_test_agent Java Project, follow this: https://stackoverflow.com/questions/10362166/maven-option-is-not-found-in-eclipse
* If "Maven build ..." does not work with the goal "mvn clean install", then set the goal as "clean install"

2. To create a JAR file of the java_test_agent Java project, goto File -> Export -> Runnable JAR File -> Launch configuration: "Main - java_test_agent" -> (Update Export Destination e.g. Downloads) -> Library handling: Extract required libraries into generated JAR -> Finish

=== Running BDD Tests

For information about running BDD Tests, refer to BDD/README.adoc

=== Cleaning Up

Clean up by running the command:
`python clean_project.py`

== Diagrams

image::screenshots/RegisterListenerv2.drawio.svg[]

*Figure 1: Test Manager --> Test Agent: Trigger Send/RegisterListener/UnregisterListener*

image::screenshots/DispatcherCommunication.drawio.svg[]

*Figure 2: Test Agent: Dispatcher Communication*

The Dispatcher is a socket-utransport-specific module, created to quickly test SDK Interoperability.

image::screenshots/TestManagerTestAgentv2.drawio.svg[]

*Figure 3: Test Manager --> Test Agent: Integrated Communication*