= Eclipse uProtocol TCK Library 
:toc:

== Overview

This library implements the uProtocol Test Compatibility Kit for the use of a Test Manager and Test Agents. A Test Manager will be responsible for sending commands to multiple connected Test Agents. The Test Agents, in turn, will carry out the tests specified in the commands, and return results back to the Test Manager for validation and processing.



== Getting Started

=== Prerequisites
Set up up-python

----
$ git clone https://github.com/eclipse-uprotocol/up-python.git
$ cd up-python
$ pip install .
----

=== Importing the up-tck-python
 
Set up upclient-socket-python local repository and install
[source]
----
$ git clone https://github.com/eclipse-uprotocol/up-tck.git
$ cd up-tck
$ pip install .
----
*This will install the up-tck-python, making its classes and modules available for import in your python code.*

=== Running Test Manager and Test Agent Examples

Test Manager uses the test_runner.txt file in the python/examples/tck_interoperability folder to define and run tests between the Test Manager and Test Agents.
Inside the test_runner.txt file, you will find various statements that can be used to trigger Test Manager behaviors.
To learn more about this grammar, please refer to the bottom section.

If you would like to run the python Test Manager and Test Agent automatically in Windows, triggering your test_runner.txt file, run python\examples\tck_interoperability\demo_windows.bat


In Linux, to run the python Test Manager and Test Agent manually, run the following commands, each command running in a separate terminal:
----
$ cd .\python\dispatcher\
$ python .\dispatcher.py
----
----
$ cd .\python\examples\tck_interoperability\
$ python .\test_socket_tm.py
----
----
$ cd .\python\examples\tck_interoperability\
$ python .\test_socket_ta.py
----

=== Running up-tck-python Socket-UTransport examples

To run the examples...

----
$ cd .\python\dispatcher\
$ python .\dispatcher.py
----
----
$ cd .\python\examples\up-client-socket-python\
$ python .\test_listener.py
----
----
$ cd .\python\examples\up-client-socket-python\
$ python .\test_sender.py
----

=== Cleaning Up

Clean up by running the command:
`python clean_project.py`

=== Appendix: Test Manager grammar 
grammar:
    <stmt-seq> := <stmt> | <stmt><stmt-seq>
    <stmt> := <register_listener> | <send> | <responds_ustatus>
    
    <register_listener> := "enactor" register_listener_command "receiver" | 
        "enactor" register_listener_command "receiver" 
        { 
            <param-list>  
        }

    <send> := "enactor" send_command "receiver" | 
        "enactor" register_listener_command "receiver" 
        { 
            <param-list>  
        }

    <responds_ustatus> := "enactor" responds_ustatus "receiver" | 
        "enactor" responds_ustatus "receiver" 
        { 
            <param-list>  
        }

    <param-list> := <param> | <param><param-list> 
    <param> := <variable> = "string" | 
        <variable> = { 
            <param-list> 
        }

    * Note: not case case sensitive
    <variable> := UUrI | UPAYLOAD | CLOUDEVENT | UAttributes | id | source
    