= Eclipse uProtocol TCK - BDD Tests
:toc:

== Overview

This Test Framework allows users to implement their own interoperability tests using the python Behave library.

=== Running BDD Tests

Behave is a python implementation of the BDD (Behavior Driven Development) style of testing.
With Behave, users can create files called "feature files," within which a test is written out in natural language.

For testing interoperability between different language test agents, users can create these feature files, specifying which languages are under test.
Specific step definitions for the test manager and test agents are located below.

==== Running BDD Example Test

Example scripts for TCK Interoperability are supplied under BDD/features/tests.
To run these example tests:

1. Go to the BDD Folder (cd BDD)
2. If in Windows, run "testrunner.bat".
When prompted, enter in the feature file name (for the example, it's "send.feature").
If in Linux, run "sh testrunner.sh".
When prompted, enter in the feature file name (for the example, it's "send.feature").

After running a BDD test, ensure that you close all opened command prompt windows before running a new test.
Your report will be located in BDD/reports.
It will be labeled with the date and time that the test was run.

If you receive a "/usr/bin/python: No module named behave" error, go into "testrunner.sh" and change "python" to "python3".

If you run into any errors related to "Connection refused", this means that something is still listening on the sockets being used to communicate.
Please try to shut those sockets down, or wait a few moments before starting the test again.

==== Writing your own BDD Tests

You can follow the format in BDD/features/tests/send.feature to see how different tests are created and formatted.
All steps in the feature file are implemented in BDD/features/steps/tck_step_implementations.py.

===== Register Listener

If you would like to trigger the "registerlistener" method within an individual Test Agent's uTransport, use the following format:

----
Given “<uE1>” creates data for "registerlistener"
    And sets "uri.entity.name" to "body.access"
    And sets "uri.resource.name" to "door"
    And sets "uri.resource.instance" to "front_left"
    And sets "uri.resource.message" to "Door"
    And sends "registerlistener" request
----

In this example, <uE1> is the uEntity that will be doing the uTransport "registerlistener" method.
The language specified will run the "registerlistener" method.

==== Send

If you would like to trigger the "send" method within an individual Test Agent's uTransport, use the following format:

----
When “<uE2>” creates data for "send"
    And sets "uri.entity.name" to "body.access"
    And sets "uri.resource.name" to "door"
    And sets "uri.resource.instance" to "front_left"
    And sets "uri.resource.message" to "Door"
    And sets "attributes.priority" to "UPRIORITY_CS1"
    And sets "attributes.type" to "UMESSAGE_TYPE_PUBLISH"
    And sets "attributes.id" to "12345"
    And sets "payload.format" to "protobuf"
    And sets "payload.value" to "serialized protobuf data"
    And sends "send" request
----

In this example, <uE2> is the uEntity that will be doing the uTransport "send" method.
The language specified will run the "send" method.

==== Examples section

This section specifies the individual tests that will be run as part of the scenario.
You create as many rows in this section as you want.
The first row specifies the variable name, and subsequent rows specify what those variables will be set to during the test.

----
Examples: topic_names
| uE1       | uE2    |
| java      | python |
| python    | java   |
----

For example, here, one test will be run where <uE1> is set to "java" and <uE2> is set to "python", and then the same test will be run with <uE1> set to "python" and <uE2> set to "java".
